[package]
name = "hybrid_encryption_process"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies]
rsa = "0.9.6"
aes =0.8.4.4"
rand = "0.8.4"
hex = "0.4.3"
