[package]
name = "file_transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
tokio = { version = "1", features = ["full"] }
async-std = "1.9.0"